### ISSUE TITLE
Crash on end

### ISSUE THREAD

**Issue by xZoidy** [CubePM/CubeBox#2]
17.03 14:02:45 [Server] Server thread/CRITICAL InvalidStateException: "Cannot schedule update on garbage entity TheAz928\CubeBox\entity\FloatingText" (EXCEPTION) in "src/pocketmine/entity/Entity" at line 1395
17.03 14:02:45 [Server] Server thread/DEBUG #0 src/pocketmine/entity/Entity(1985): pocketmine\entity\Entity->scheduleUpdate()
17.03 14:02:45 [Server] Server thread/DEBUG #1 plugins/CubeBox-master/src/TheAz928/CubeBox/tile/CrateTile(128): pocketmine\entity\Entity->flagForDespawn()

**Comment by TheAz928** [comment]
please provide the full crash dumb and your plugin list.

**Comment by TheAz928** [comment]
Since you didn't provided crashdumps, and similar issue happened to other people, but I diagnosed it and found "entiry clear" plugin clearing the crate entities. So this issue is invalid.
