### ISSUE TITLE
unnecessary particles

### ISSUE THREAD

**Issue by Mainek** [CubePM/CubeBox#7]
![2020_04_25_17 17 53](https://user-images.githubusercontent.com/59147402/80282580-d1624800-871a-11ea-8f8d-2cb34ecb986c.jpg)
![2020_04_25_17 17 20](https://user-images.githubusercontent.com/59147402/80282587-da531980-871a-11ea-9e1a-5d58f2f18ac1.jpg)
there are many of them in the corner of the chest

**Comment by TheAz928** [comment]
Probably lag, but I'll take a look.

**Comment by Mainek** [comment]
definitely not a delay
