### ISSUE TITLE
zombies will not spawn with this plugin 

### ISSUE THREAD

**Issue by Mainek** [CubePM/CubeBox#8]
zombies will not spawn with this plugin  and it is a fact pmmp 1.14.60 verified separately from other plugins

**Comment by Mainek** [comment]
no need to deny the facts

**Comment by Mainek** [comment]
I apologize for my English. I am from Russia

**Comment by TheAz928** [comment]
This plugin has nothing to do with zombies.

**Comment by Mainek** [comment]
no has i seen

**Comment by Mainek** [comment]
look in floatingtext.php
